# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vevdHMR73Ha4BvagmPUPwelBj7jO7Kcm
"""

name = input("Enter your name: ")
ticket_type = input("Enter ticket type (Regular/VIP): ").lower()

try:
  quantity = int(input("Enter number of tickets: "))
except:
  print("Invalid number")
  exit()

if ticket_type == "regular":
  price = 500
elif ticket_type == "vip":
  price = 1000
else:
  print("Invalid ticket type")
  exit()

total = price *  quantity


if total > 3000:
  discount = total * 0.10
else:
  discount = 0

final_amount = total - discount

print("\n Movie Ticket Bill")
print("Name:", name)
print("Ticket_Type:", ticket_type.capitalize())
print("Tickets:", quantity)
print("Total: Rs.", total)
print("Discount: Rs.", discount)
print("Final Amount: Rs.",final_amount)